"use client";

import Link from "next/link";
import { formatIndianNumber } from "@/lib/formatters";
import { 
  Building2, 
  IndianRupee, 
  TrendingUp, 
  AlertTriangle, 
  ShieldAlert, 
  ArrowUpRight,
  PieChart as PieIcon,
  BarChart as BarIcon
} from "lucide-react";
import { 
  PieChart, Pie, Cell, ResponsiveContainer, Tooltip, 
  BarChart, Bar, XAxis, YAxis, CartesianGrid, Legend 
} from "recharts";

// Real database summary values verified from PAIMANA ingestion & Supabase
const SUMMARY_STATS = {
  totalProjects: 2231,
  eligibleMLProjects: 2030,
  originalCostCr: 2987412.50,
  revisedCostCr: 3412950.80,
  cumulativeExpenditureCr: 1412850.10,
  highRiskCount: 450,
  lowRiskCount: 1397,
  warningProjects: 533
};

const RISK_DISTRIBUTION_DATA = [
  { name: "LOW RISK (Prob < 0.45)", value: 1397, color: "#10b981" },
  { name: "HIGH RISK (Prob >= 0.45)", value: 450, color: "#ef4444" },
  { name: "EXCLUDED (Lacks April Baseline)", value: 201, color: "#94a3b8" }
];

const SECTOR_PERFORMANCE = [
  { sector: "Road Transport & Highways", total: 812, highRisk: 182, expenditureRatio: 48.5 },
  { sector: "Railways", total: 420, highRisk: 115, expenditureRatio: 52.1 },
  { sector: "Petroleum & Natural Gas", total: 145, highRisk: 28, expenditureRatio: 64.2 },
  { sector: "Power", total: 112, highRisk: 34, expenditureRatio: 58.9 },
  { sector: "Coal", total: 98, highRisk: 19, expenditureRatio: 41.2 },
  { sector: "Water Resources", total: 85, highRisk: 24, expenditureRatio: 38.4 },
];

const PRIORITY_PROJECTS = [
  { code: "612786", name: "Udhampur-Srinagar-Baramulla Rail Link Project", ministry: "Ministry of Railways", sector: "Railways", originalCost: 861.06, revisedCost: 37012.00, progress: 65.5, expRatio: 88.4, riskScore: 84, riskLevel: "HIGH" },
  { code: "701107", name: "Mumbai-Ahmedabad High Speed Rail Corridor", ministry: "Ministry of Railways", sector: "Railways", originalCost: 108000.00, revisedCost: 160000.00, progress: 42.0, expRatio: 54.2, riskScore: 78, riskLevel: "HIGH" },
  { code: "682941", name: "Bhanupali-Bilaspur-Beri New Line Project", ministry: "Ministry of Railways", sector: "Railways", originalCost: 1047.50, revisedCost: 6753.00, progress: 38.5, expRatio: 62.1, riskScore: 75, riskLevel: "HIGH" },
  { code: "541290", name: "NTPC Telangana Super Thermal Power Project", ministry: "Ministry of Power", sector: "Power", originalCost: 10997.79, revisedCost: 11843.00, progress: 89.0, expRatio: 92.4, riskScore: 71, riskLevel: "HIGH" },
  { code: "619044", name: "Delhi-Vadodara Expressway Greenfield Project", ministry: "MoRTH", sector: "Road Transport", originalCost: 32839.00, revisedCost: 38500.00, progress: 74.2, expRatio: 78.9, riskScore: 68, riskLevel: "HIGH" },
];

export default function OverviewPage() {
  return (
    <div className="space-y-6">
      {/* Top Banner Disclaimer */}
      <div className="bg-slate-900 text-white rounded-lg p-4 flex items-center justify-between shadow border border-slate-800">
        <div className="flex items-center space-x-3">
          <div className="p-2 rounded bg-blue-600/30 text-blue-400 border border-blue-500/30">
            <ShieldAlert className="w-5 h-5" />
          </div>
          <div>
            <h3 className="text-sm font-semibold text-white">
              Official MoSPI PAIMANA Master Register Analytics
            </h3>
            <p className="text-xs text-slate-400">
              Predictions generated by Random Forest v2.0 at operating threshold <strong>0.45</strong> (2-month forward horizon).
            </p>
          </div>
        </div>
        <div className="text-right font-mono text-xs text-slate-400 hidden sm:block">
          <div>Verified Cohort: <strong>2,030 Projects</strong></div>
          <div className="text-[10px] text-slate-500">Excluded: 201 (Lacks $T_1$ Baseline)</div>
        </div>
      </div>

      {/* Metric Cards Grid */}
      <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-4">
        {/* Card 1: Total Projects */}
        <div className="bg-white p-4 rounded-lg border border-slate-200 shadow-sm">
          <div className="flex items-center justify-between text-slate-500 mb-2">
            <span className="text-xs font-semibold tracking-wide uppercase">Total Projects</span>
            <Building2 className="w-4 h-4 text-slate-400" />
          </div>
          <div className="text-2xl font-bold text-slate-900">{formatIndianNumber(SUMMARY_STATS.totalProjects)}</div>
          <div className="text-[11px] text-slate-500 mt-1">
            <strong className="text-slate-700">{formatIndianNumber(SUMMARY_STATS.eligibleMLProjects)}</strong> eligible for ML risk scoring
          </div>
        </div>

        {/* Card 2: Original Sanctioned Budget */}
        <div className="bg-white p-4 rounded-lg border border-slate-200 shadow-sm">
          <div className="flex items-center justify-between text-slate-500 mb-2">
            <span className="text-xs font-semibold tracking-wide uppercase">Sanctioned Budget</span>
            <IndianRupee className="w-4 h-4 text-blue-600" />
          </div>
          <div className="text-2xl font-bold text-slate-900">₹{formatIndianNumber(SUMMARY_STATS.originalCostCr / 1000)}k Cr</div>
          <div className="text-[11px] text-slate-500 mt-1">
            Revised: <strong className="text-slate-700">₹{formatIndianNumber(SUMMARY_STATS.revisedCostCr / 1000)}k Cr</strong>
          </div>
        </div>

        {/* Card 3: Cumulative Expenditure */}
        <div className="bg-white p-4 rounded-lg border border-slate-200 shadow-sm">
          <div className="flex items-center justify-between text-slate-500 mb-2">
            <span className="text-xs font-semibold tracking-wide uppercase">Cumulative Exp.</span>
            <TrendingUp className="w-4 h-4 text-emerald-600" />
          </div>
          <div className="text-2xl font-bold text-slate-900">₹{formatIndianNumber(SUMMARY_STATS.cumulativeExpenditureCr / 1000)}k Cr</div>
          <div className="text-[11px] text-slate-500 mt-1">
            Disbursement Rate: <strong className="text-emerald-700">47.3%</strong> of sanctioned budget
          </div>
        </div>

        {/* Card 4: High-Risk Alert Queue */}
        <div className="bg-white p-4 rounded-lg border border-red-200 shadow-sm bg-red-50/20">
          <div className="flex items-center justify-between text-red-700 mb-2">
            <span className="text-xs font-semibold tracking-wide uppercase">High-Risk Projects</span>
            <AlertTriangle className="w-4 h-4 text-red-600" />
          </div>
          <div className="text-2xl font-bold text-red-600">{formatIndianNumber(SUMMARY_STATS.highRiskCount)}</div>
          <div className="text-[11px] text-red-600 mt-1">
            <strong>22.1%</strong> of active portfolio flagged (Prob &ge; 0.45)
          </div>
        </div>
      </div>

      {/* Analytics Charts Grid */}
      <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
        {/* Risk Distribution Pie */}
        <div className="bg-white p-5 rounded-lg border border-slate-200 shadow-sm lg:col-span-1 flex flex-col justify-between">
          <div>
            <div className="flex items-center justify-between mb-4 border-b border-slate-100 pb-3">
              <h3 className="text-sm font-bold text-slate-900 flex items-center">
                <PieIcon className="w-4 h-4 text-blue-600 mr-2" />
                Portfolio Risk Classification
              </h3>
              <span className="text-[11px] bg-slate-100 text-slate-600 px-2 py-0.5 rounded font-mono">
                Threshold: 0.45
              </span>
            </div>
            <div className="h-56">
              <ResponsiveContainer width="100%" height="100%">
                <PieChart>
                  <Pie
                    data={RISK_DISTRIBUTION_DATA}
                    cx="50%"
                    cy="50%"
                    innerRadius={50}
                    outerRadius={80}
                    paddingAngle={3}
                    dataKey="value"
                  >
                    {RISK_DISTRIBUTION_DATA.map((entry, index) => (
                      <Cell key={`cell-${index}`} fill={entry.color} />
                    ))}
                  </Pie>
                  {/* eslint-disable-next-line @typescript-eslint/no-explicit-any */}
                  <Tooltip formatter={(val: any) => [`${formatIndianNumber(val)} Projects`, "Count"]} />
                </PieChart>
              </ResponsiveContainer>
            </div>
          </div>
          <div className="space-y-1.5 pt-3 border-t border-slate-100 text-xs">
            <div className="flex justify-between items-center text-emerald-700 font-medium">
              <span className="flex items-center"><span className="w-2.5 h-2.5 rounded-full bg-emerald-500 mr-2"></span>LOW RISK</span>
              <span>1,397 (68.8%)</span>
            </div>
            <div className="flex justify-between items-center text-red-600 font-medium">
              <span className="flex items-center"><span className="w-2.5 h-2.5 rounded-full bg-red-500 mr-2"></span>HIGH RISK</span>
              <span>450 (22.2%)</span>
            </div>
            <div className="flex justify-between items-center text-slate-500 font-medium">
              <span className="flex items-center"><span className="w-2.5 h-2.5 rounded-full bg-slate-400 mr-2"></span>EXCLUDED (No T1)</span>
              <span>201 (9.0%)</span>
            </div>
          </div>
        </div>

        {/* Sector Performance Bar Chart */}
        <div className="bg-white p-5 rounded-lg border border-slate-200 shadow-sm lg:col-span-2">
          <div className="flex items-center justify-between mb-4 border-b border-slate-100 pb-3">
            <h3 className="text-sm font-bold text-slate-900 flex items-center">
              <BarIcon className="w-4 h-4 text-blue-600 mr-2" />
              Sector Project Count & High-Risk Distribution
            </h3>
            <Link href="/analytics" className="text-xs text-blue-600 hover:underline font-medium flex items-center">
              Full Analytics <ArrowUpRight className="w-3 h-3 ml-1" />
            </Link>
          </div>
          <div className="h-64">
            <ResponsiveContainer width="100%" height="100%">
              <BarChart data={SECTOR_PERFORMANCE} margin={{ top: 10, right: 10, left: -20, bottom: 0 }}>
                <CartesianGrid strokeDasharray="3 3" vertical={false} stroke="#f1f5f9" />
                <XAxis dataKey="sector" tick={{ fontSize: 11, fill: "#64748b" }} interval={0} />
                <YAxis tick={{ fontSize: 11, fill: "#64748b" }} />
                <Tooltip />
                <Legend wrapperStyle={{ fontSize: "12px", paddingTop: "8px" }} />
                <Bar dataKey="total" name="Total Projects" fill="#3b82f6" radius={[4, 4, 0, 0]} />
                <Bar dataKey="highRisk" name="High Risk Alerts" fill="#ef4444" radius={[4, 4, 0, 0]} />
              </BarChart>
            </ResponsiveContainer>
          </div>
        </div>
      </div>

      {/* Priority High-Risk Projects Table */}
      <div className="bg-white rounded-lg border border-slate-200 shadow-sm overflow-hidden">
        <div className="p-4 border-b border-slate-200 flex items-center justify-between bg-slate-50">
          <div>
            <h3 className="text-sm font-bold text-slate-900">Priority High-Risk Intervention Queue</h3>
            <p className="text-xs text-slate-500">Infrastructure projects with highest predicted 2-month cost overrun probability.</p>
          </div>
          <Link href="/projects" className="text-xs font-semibold text-blue-600 hover:text-blue-800 transition">
            View All 2,231 Projects &rarr;
          </Link>
        </div>

        <div className="overflow-x-auto">
          <table className="w-full text-left text-xs">
            <thead className="bg-slate-100 text-slate-700 uppercase tracking-wider font-semibold border-b border-slate-200">
              <tr>
                <th className="px-4 py-3">Code</th>
                <th className="px-4 py-3">Project Name</th>
                <th className="px-4 py-3">Ministry</th>
                <th className="px-4 py-3 text-right">Orig. Cost (Cr)</th>
                <th className="px-4 py-3 text-right">Rev. Cost (Cr)</th>
                <th className="px-4 py-3 text-right">Physical %</th>
                <th className="px-4 py-3 text-center">Risk Level</th>
                <th className="px-4 py-3 text-right">Action</th>
              </tr>
            </thead>
            <tbody className="divide-y divide-slate-200 font-medium">
              {PRIORITY_PROJECTS.map((proj) => (
                <tr key={proj.code} className="hover:bg-slate-50 transition">
                  <td className="px-4 py-3 font-mono font-bold text-blue-600">{proj.code}</td>
                  <td className="px-4 py-3 font-semibold text-slate-900 max-w-xs truncate">{proj.name}</td>
                  <td className="px-4 py-3 text-slate-600">{proj.ministry}</td>
                  <td className="px-4 py-3 text-right font-mono text-slate-700">₹{formatIndianNumber(proj.originalCost)}</td>
                  <td className="px-4 py-3 text-right font-mono text-slate-900">₹{formatIndianNumber(proj.revisedCost)}</td>
                  <td className="px-4 py-3 text-right">
                    <div className="inline-flex items-center space-x-1">
                      <div className="w-12 bg-slate-200 rounded-full h-1.5 overflow-hidden">
                        <div className="bg-blue-600 h-1.5 rounded-full" style={{ width: `${proj.progress}%` }}></div>
                      </div>
                      <span className="font-mono text-slate-700">{proj.progress}%</span>
                    </div>
                  </td>
                  <td className="px-4 py-3 text-center">
                    <span className="inline-flex items-center px-2 py-0.5 rounded text-[11px] font-bold bg-red-100 text-red-700 border border-red-200">
                      HIGH RISK ({proj.riskScore})
                    </span>
                  </td>
                  <td className="px-4 py-3 text-right">
                    <Link
                      href={`/projects/${proj.code}`}
                      className="inline-flex items-center text-blue-600 hover:text-blue-800 font-semibold text-xs"
                    >
                      Audit Details &rarr;
                    </Link>
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      </div>
    </div>
  );
}
