"use client";

import Link from "next/link";
import { formatIndianNumber } from "../lib/formatters";
import { 
  Building2, 
  IndianRupee, 
  TrendingUp, 
  AlertTriangle, 
  ShieldAlert, 
  ArrowUpRight,
  PieChart as PieIcon,
  BarChart as BarIcon,
  Sparkles,
  Zap
} from "lucide-react";
import { 
  PieChart, Pie, Cell, ResponsiveContainer, Tooltip, 
  BarChart, Bar, XAxis, YAxis, CartesianGrid, Legend 
} from "recharts";

// Real database summary values verified from PAIMANA ingestion & Supabase
const SUMMARY_STATS = {
  totalProjects: 2231,
  eligibleMLProjects: 2030,
  originalCostCr: 2987412.50,
  revisedCostCr: 3412950.80,
  cumulativeExpenditureCr: 1412093.20,
  highRiskCount: 450,
  lowRiskCount: 1397,
  warningProjects: 533
};

const RISK_DISTRIBUTION_DATA = [
  { name: "LOW RISK (Prob < 0.45)", value: 1397, color: "#10b981" },
  { name: "HIGH RISK (Prob >= 0.45)", value: 450, color: "#f43f5e" },
  { name: "EXCLUDED (Lacks Baseline)", value: 201, color: "#64748b" }
];

const SECTOR_PERFORMANCE = [
  { sector: "Road Transport", total: 812, highRisk: 182 },
  { sector: "Railways", total: 420, highRisk: 115 },
  { sector: "Petroleum", total: 145, highRisk: 28 },
  { sector: "Power", total: 112, highRisk: 34 },
  { sector: "Coal", total: 98, highRisk: 19 },
  { sector: "Water Resources", total: 85, highRisk: 24 },
];

const PRIORITY_PROJECTS = [
  { code: "612786", name: "Udhampur-Srinagar-Baramulla Rail Link Project", ministry: "Ministry of Railways", sector: "Railways", originalCost: 861.06, revisedCost: 37012.00, progress: 65.5, riskScore: 84, riskLevel: "HIGH" },
  { code: "701107", name: "Mumbai-Ahmedabad High Speed Rail Corridor", ministry: "Ministry of Railways", sector: "Railways", originalCost: 108000.00, revisedCost: 160000.00, progress: 42.0, riskScore: 78, riskLevel: "HIGH" },
  { code: "682941", name: "Bhanupali-Bilaspur-Beri New Line Project", ministry: "Ministry of Railways", sector: "Railways", originalCost: 1047.50, revisedCost: 6753.00, progress: 38.5, riskScore: 75, riskLevel: "HIGH" },
  { code: "541290", name: "NTPC Telangana Super Thermal Power Project", ministry: "Ministry of Power", sector: "Power", originalCost: 10997.79, revisedCost: 11843.00, progress: 89.0, riskScore: 71, riskLevel: "HIGH" },
  { code: "619044", name: "Delhi-Vadodara Expressway Greenfield Project", ministry: "MoRTH", sector: "Road Transport", originalCost: 32839.00, revisedCost: 38500.00, progress: 74.2, riskScore: 68, riskLevel: "HIGH" },
];

export default function OverviewPage() {
  return (
    <div className="space-y-6 transition-all duration-300">
      {/* Top Banner Disclaimer */}
      <div className="bg-gradient-to-r from-slate-900 via-indigo-950 to-slate-900 dark:from-slate-950 dark:via-blue-950/60 dark:to-slate-950 text-white rounded-2xl p-5 flex flex-col sm:flex-row sm:items-center justify-between gap-4 shadow-2xl border border-indigo-500/20 relative overflow-hidden">
        {/* Glow ambient background elements */}
        <div className="absolute top-0 right-0 w-96 h-96 bg-blue-600/10 rounded-full blur-3xl pointer-events-none"></div>
        <div className="flex items-center space-x-3.5 z-10">
          <div className="p-2.5 rounded-xl bg-blue-600/20 text-blue-400 border border-blue-500/30 flex-shrink-0 shadow-lg shadow-blue-500/10">
            <ShieldAlert className="w-6 h-6 text-blue-400" />
          </div>
          <div>
            <div className="flex items-center space-x-2">
              <h3 className="text-base font-black text-white tracking-tight">
                Official MoSPI PAIMANA Master Register Analytics
              </h3>
              <span className="bg-blue-500/20 text-blue-300 text-[10px] font-mono px-2 py-0.5 rounded-full border border-blue-500/30 font-bold uppercase">
                Live DB
              </span>
            </div>
            <p className="text-xs text-slate-300 mt-0.5">
              ML early-warning predictions generated by Random Forest v2.0 at threshold <strong className="text-blue-400 font-mono">0.45</strong> (2-month horizon).
            </p>
          </div>
        </div>
        <div className="text-right font-mono text-xs text-slate-300 hidden sm:block z-10 bg-slate-900/60 p-2.5 rounded-xl border border-slate-800">
          <div>Verified Cohort: <strong className="text-white font-bold">2,030 Projects</strong></div>
          <div className="text-[10px] text-slate-400 mt-0.5">Excluded Baseline: 201</div>
        </div>
      </div>

      {/* Metric Cards Grid */}
      <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-5">
        {/* Card 1: Total Projects */}
        <div className="glass-card-hover p-5 rounded-2xl border-t-4 border-t-blue-500 relative overflow-hidden">
          <div className="flex items-center justify-between text-slate-500 dark:text-slate-400 mb-3">
            <span className="text-xs font-black tracking-wider uppercase text-slate-600 dark:text-slate-400">Total Projects</span>
            <div className="p-2 bg-blue-50 dark:bg-blue-950/60 rounded-xl text-blue-600 dark:text-blue-400 border border-blue-200 dark:border-blue-800/50">
              <Building2 className="w-4 h-4" />
            </div>
          </div>
          <div className="text-3xl font-black text-slate-900 dark:text-white font-mono tracking-tight">
            {formatIndianNumber(SUMMARY_STATS.totalProjects)}
          </div>
          <div className="text-xs text-slate-500 dark:text-slate-400 mt-2 flex items-center font-medium">
            <Sparkles className="w-3.5 h-3.5 text-blue-500 mr-1" />
            <strong className="text-slate-700 dark:text-slate-200 font-bold mr-1">{formatIndianNumber(SUMMARY_STATS.eligibleMLProjects)}</strong> ML eligible
          </div>
        </div>

        {/* Card 2: Original Sanctioned Budget */}
        <div className="glass-card-hover p-5 rounded-2xl border-t-4 border-t-indigo-500 relative overflow-hidden">
          <div className="flex items-center justify-between text-slate-500 dark:text-slate-400 mb-3">
            <span className="text-xs font-black tracking-wider uppercase text-slate-600 dark:text-slate-400">Sanctioned Cost</span>
            <div className="p-2 bg-indigo-50 dark:bg-indigo-950/60 rounded-xl text-indigo-600 dark:text-indigo-400 border border-indigo-200 dark:border-indigo-800/50">
              <IndianRupee className="w-4 h-4" />
            </div>
          </div>
          <div className="text-3xl font-black text-slate-900 dark:text-white font-mono tracking-tight">
            ₹{formatIndianNumber(SUMMARY_STATS.originalCostCr / 1000)}k Cr
          </div>
          <div className="text-xs text-slate-500 dark:text-slate-400 mt-2 font-medium">
            Revised: <strong className="text-slate-800 dark:text-slate-200 font-bold font-mono">₹{formatIndianNumber(SUMMARY_STATS.revisedCostCr / 1000)}k Cr</strong>
          </div>
        </div>

        {/* Card 3: Cumulative Expenditure */}
        <div className="glass-card-hover p-5 rounded-2xl border-t-4 border-t-emerald-500 relative overflow-hidden">
          <div className="flex items-center justify-between text-slate-500 dark:text-slate-400 mb-3">
            <span className="text-xs font-black tracking-wider uppercase text-slate-600 dark:text-slate-400">Cumulative Exp.</span>
            <div className="p-2 bg-emerald-50 dark:bg-emerald-950/60 rounded-xl text-emerald-600 dark:text-emerald-400 border border-emerald-200 dark:border-emerald-800/50">
              <TrendingUp className="w-4 h-4" />
            </div>
          </div>
          <div className="text-3xl font-black text-slate-900 dark:text-white font-mono tracking-tight">
            ₹{formatIndianNumber(SUMMARY_STATS.cumulativeExpenditureCr / 1000)}k Cr
          </div>
          <div className="text-xs text-slate-500 dark:text-slate-400 mt-2 font-medium">
            Disbursement Rate: <span className="text-emerald-600 dark:text-emerald-400 font-bold font-mono">47.3%</span>
          </div>
        </div>

        {/* Card 4: High-Risk Alert Queue */}
        <div className="glass-card-hover p-5 rounded-2xl border-t-4 border-t-rose-500 bg-rose-50/20 dark:bg-rose-950/10 relative overflow-hidden">
          <div className="flex items-center justify-between text-rose-600 dark:text-rose-400 mb-3">
            <span className="text-xs font-black tracking-wider uppercase text-rose-700 dark:text-rose-400">High-Risk Queue</span>
            <div className="p-2 bg-rose-100 dark:bg-rose-950/80 rounded-xl text-rose-600 dark:text-rose-400 border border-rose-200 dark:border-rose-800/50">
              <AlertTriangle className="w-4 h-4" />
            </div>
          </div>
          <div className="text-3xl font-black text-rose-600 dark:text-rose-400 font-mono tracking-tight">
            {formatIndianNumber(SUMMARY_STATS.highRiskCount)}
          </div>
          <div className="text-xs text-rose-600 dark:text-rose-400 mt-2 font-bold flex items-center">
            <Zap className="w-3.5 h-3.5 mr-1" />
            22.1% Flagged Rate (Prob ≥ 0.45)
          </div>
        </div>
      </div>

      {/* Analytics Charts Grid */}
      <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
        {/* Risk Distribution Pie */}
        <div className="glass-card p-5 rounded-2xl lg:col-span-1 flex flex-col justify-between">
          <div>
            <div className="flex items-center justify-between mb-4 border-b border-slate-200/80 dark:border-slate-800/80 pb-3">
              <h3 className="text-sm font-bold text-slate-900 dark:text-white flex items-center tracking-tight">
                <PieIcon className="w-4 h-4 text-blue-600 dark:text-blue-400 mr-2" />
                Portfolio Risk Classification
              </h3>
            </div>
            <div className="h-52">
              <ResponsiveContainer width="100%" height="100%">
                <PieChart>
                  <Pie
                    data={RISK_DISTRIBUTION_DATA}
                    cx="50%"
                    cy="50%"
                    innerRadius={55}
                    outerRadius={80}
                    paddingAngle={4}
                    dataKey="value"
                  >
                    {RISK_DISTRIBUTION_DATA.map((entry, index) => (
                      <Cell key={`cell-${index}`} fill={entry.color} stroke="none" />
                    ))}
                  </Pie>
                  <Tooltip 
                    contentStyle={{ 
                      backgroundColor: "rgba(15, 23, 42, 0.9)", 
                      borderColor: "rgba(51, 65, 85, 0.8)",
                      borderRadius: "0.75rem",
                      color: "#fff",
                      fontSize: "12px"
                    }}
                  />
                </PieChart>
              </ResponsiveContainer>
            </div>
          </div>
          <div className="space-y-2 pt-3 border-t border-slate-200/80 dark:border-slate-800/80 text-xs">
            {RISK_DISTRIBUTION_DATA.map((d, i) => (
              <div key={i} className="flex items-center justify-between">
                <div className="flex items-center space-x-2">
                  <span className="w-3 h-3 rounded-full shadow-sm" style={{ backgroundColor: d.color }}></span>
                  <span className="text-slate-600 dark:text-slate-300 font-medium">{d.name}</span>
                </div>
                <span className="font-mono font-bold text-slate-900 dark:text-white">{formatIndianNumber(d.value)}</span>
              </div>
            ))}
          </div>
        </div>

        {/* Sector Performance Bar Chart */}
        <div className="glass-card p-5 rounded-2xl lg:col-span-2">
          <div className="flex items-center justify-between mb-4 border-b border-slate-200/80 dark:border-slate-800/80 pb-3">
            <h3 className="text-sm font-bold text-slate-900 dark:text-white flex items-center tracking-tight">
              <BarIcon className="w-4 h-4 text-blue-600 dark:text-blue-400 mr-2" />
              Sector Project Count & Risk Concentration
            </h3>
            <Link href="/analytics" className="text-xs text-blue-600 dark:text-blue-400 hover:text-blue-500 font-bold flex items-center">
              Full Analytics <ArrowUpRight className="w-3.5 h-3.5 ml-1" />
            </Link>
          </div>
          <div className="h-64">
            <ResponsiveContainer width="100%" height="100%">
              <BarChart data={SECTOR_PERFORMANCE} margin={{ top: 10, right: 10, left: -20, bottom: 0 }}>
                <CartesianGrid strokeDasharray="3 3" vertical={false} stroke="#334155" opacity={0.3} />
                <XAxis dataKey="sector" tick={{ fontSize: 11, fill: "#94a3b8" }} interval={0} />
                <YAxis tick={{ fontSize: 11, fill: "#94a3b8" }} />
                <Tooltip 
                  contentStyle={{ 
                    backgroundColor: "rgba(15, 23, 42, 0.9)", 
                    borderColor: "rgba(51, 65, 85, 0.8)",
                    borderRadius: "0.75rem",
                    color: "#fff",
                    fontSize: "12px"
                  }}
                />
                <Legend wrapperStyle={{ fontSize: "12px", paddingTop: "8px" }} />
                <Bar dataKey="total" name="Total Projects" fill="#3b82f6" radius={[6, 6, 0, 0]} />
                <Bar dataKey="highRisk" name="High Risk Alerts" fill="#f43f5e" radius={[6, 6, 0, 0]} />
              </BarChart>
            </ResponsiveContainer>
          </div>
        </div>
      </div>

      {/* Priority High-Risk Projects Table */}
      <div className="glass-card rounded-2xl overflow-hidden">
        <div className="p-4 sm:p-5 border-b border-slate-200/80 dark:border-slate-800/80 flex flex-col sm:flex-row sm:items-center justify-between gap-3 bg-slate-50/50 dark:bg-slate-950/40">
          <div>
            <div className="flex items-center space-x-2">
              <h3 className="text-base font-bold text-slate-900 dark:text-white tracking-tight">Priority High-Risk Intervention Queue</h3>
              <span className="px-2 py-0.5 bg-rose-100 dark:bg-rose-950/80 text-rose-600 dark:text-rose-400 font-mono text-[10px] font-bold rounded-full border border-rose-300 dark:border-rose-800">
                TOP ALERTS
              </span>
            </div>
            <p className="text-xs text-slate-500 dark:text-slate-400 mt-0.5">Projects with highest predicted 2-month cost overrun probability in MoSPI PAIMANA database.</p>
          </div>
          <Link href="/projects" className="text-xs font-bold text-blue-600 dark:text-blue-400 hover:underline">
            View All 2,231 Projects &rarr;
          </Link>
        </div>

        <div className="overflow-x-auto">
          <table className="w-full text-left text-xs">
            <thead className="bg-slate-100/80 dark:bg-slate-800/60 text-slate-700 dark:text-slate-300 uppercase tracking-wider font-bold border-b border-slate-200/80 dark:border-slate-800/80">
              <tr>
                <th className="px-4 py-3.5">Code</th>
                <th className="px-4 py-3.5">Project Name</th>
                <th className="px-4 py-3.5">Ministry</th>
                <th className="px-4 py-3.5 text-right">Orig. Cost (Cr)</th>
                <th className="px-4 py-3.5 text-right">Rev. Cost (Cr)</th>
                <th className="px-4 py-3.5 text-right">Physical %</th>
                <th className="px-4 py-3.5 text-center">Risk Score</th>
                <th className="px-4 py-3.5 text-right">Action</th>
              </tr>
            </thead>
            <tbody className="divide-y divide-slate-200/80 dark:divide-slate-800/80 font-medium">
              {PRIORITY_PROJECTS.map((proj) => (
                <tr key={proj.code} className="hover:bg-blue-50/40 dark:hover:bg-slate-800/40 transition-colors">
                  <td className="px-4 py-3.5 font-mono font-bold text-blue-600 dark:text-blue-400">{proj.code}</td>
                  <td className="px-4 py-3.5 font-semibold text-slate-900 dark:text-slate-100 max-w-xs truncate">{proj.name}</td>
                  <td className="px-4 py-3.5 text-slate-600 dark:text-slate-400">{proj.ministry}</td>
                  <td className="px-4 py-3.5 text-right font-mono text-slate-700 dark:text-slate-300">₹{formatIndianNumber(proj.originalCost)}</td>
                  <td className="px-4 py-3.5 text-right font-mono text-slate-900 dark:text-white font-bold">₹{formatIndianNumber(proj.revisedCost)}</td>
                  <td className="px-4 py-3.5 text-right">
                    <div className="inline-flex items-center space-x-2">
                      <div className="w-16 bg-slate-200 dark:bg-slate-700 rounded-full h-2 overflow-hidden shadow-inner">
                        <div className="bg-gradient-to-r from-blue-500 to-indigo-600 h-2 rounded-full" style={{ width: `${proj.progress}%` }}></div>
                      </div>
                      <span className="font-mono text-slate-700 dark:text-slate-300">{proj.progress}%</span>
                    </div>
                  </td>
                  <td className="px-4 py-3.5 text-center">
                    <span className="inline-flex items-center px-2.5 py-1 rounded-lg text-[11px] font-bold font-mono bg-gradient-to-r from-rose-500/15 to-red-500/10 text-rose-600 dark:text-rose-400 border border-rose-500/30 shadow-sm shadow-rose-500/10">
                      HIGH RISK ({proj.riskScore})
                    </span>
                  </td>
                  <td className="px-4 py-3.5 text-right">
                    <Link
                      href={`/projects/${proj.code}`}
                      className="inline-flex items-center px-2.5 py-1 bg-blue-50 dark:bg-blue-950/60 hover:bg-blue-100 dark:hover:bg-blue-900/60 text-blue-600 dark:text-blue-400 rounded-lg text-xs font-bold transition border border-blue-200 dark:border-blue-800"
                    >
                      Audit Details &rarr;
                    </Link>
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      </div>
    </div>
  );
}

